-- 제조사 등록
insert into makers(maker) values('현대');
insert into makers(maker) values('기아');
insert into makers(maker) values('르노');
insert into makers(maker) values('쉐보레');
insert into makers(maker) values('쌍용');
-- 모델등록 모델명, 제조사 번호 1 현대 2 기아 3르노 4 쉐보레 5 쌍용
-- 현대
insert into model(model, mkno) values('i40 Saloon 2.0 GDI ',1);
insert into model(model, mkno) values('i40 Saloon 1.7디젤 ISG ',1);
insert into model(model, mkno) values('i40 2.0 GDI ',1);
insert into model(model, mkno) values('i40 1.7디젤 ISG ',1);
insert into model(model, mkno) values('i30 2.0 GDI (2015년형) ',1);
insert into model(model, mkno) values('i30 1.6디젤 ',1);
insert into model(model, mkno) values('포터 2.5디젤 ',1);
insert into model(model, mkno) values('투싼 2.0 GDI 2WD ',1);
insert into model(model, mkno) values('투싼 2.0디젤 4WD ',1);
insert into model(model, mkno) values('투싼 2.0디젤 2WD (TL) ',1);
insert into model(model, mkno) values('투싼 2.0디젤 2WD ISG ',1);
insert into model(model, mkno) values('투싼 2.0디젤 2WD ',1);
insert into model(model, mkno) values('투싼 1.7디젤 DCT ISG(TL) ',1);
insert into model(model, mkno) values('제네시스 쿠페 3.8 GDI ',1);
insert into model(model, mkno) values('제네시스 쿠페 2.0 TCI ',1);
insert into model(model, mkno) values('제네시스 3.8GDI AWD ',1);
insert into model(model, mkno) values('제네시스 3.8GDI 2WD ',1);
insert into model(model, mkno) values('제네시스 3.3GDI AWD ',1);
insert into model(model, mkno) values('제네시스 3.3GDI 2WD ',1);
insert into model(model, mkno) values('엑센트 카파 1.4 가솔린 ',1);
insert into model(model, mkno) values('엑센트 1.6 GDI ',1);
insert into model(model, mkno) values('엑센트 1.6 디젤 ',1);
insert into model(model, mkno) values('엑센트 1.6 디젤 DCT ',1);
insert into model(model, mkno) values('에쿠스리무진 5.0 GDI ',1);
insert into model(model, mkno) values('에쿠스리무진 3.8 GDI ',1);
insert into model(model, mkno) values('에쿠스 5.0 GDI ',1);
insert into model(model, mkno) values('에쿠스 3.8 GDI ',1);
insert into model(model, mkno) values('아슬란 3.3 GDI ',1);
insert into model(model, mkno) values('아슬란 3.0 GDI ',1);
insert into model(model, mkno) values('아반떼쿠페 2.0 가솔린 ',1);
insert into model(model, mkno) values('아반떼 1.6 LPI  ',1);
insert into model(model, mkno) values('아반떼 1.6 GDI ',1);
insert into model(model, mkno) values('아반떼 1.6 디젤 ISG ',1);
insert into model(model, mkno) values('아반떼 1.6 디젤 ',1);
insert into model(model, mkno) values('쏘나타(LF) 2.4 GDI ',1);
insert into model(model, mkno) values('쏘나타(LF) 2.0 LPI ',1);
insert into model(model, mkno) values('쏘나타(LF) 2.0 가솔린 ',1);
insert into model(model, mkno) values('쏘나타(LF) 1.7 디젤 7DCT_ISG ',1);
insert into model(model, mkno) values('쏘나타(LF) 1.6T-GDI_7DCT ',1);
insert into model(model, mkno) values('쏘나타 2.0 LPI ',1);
insert into model(model, mkno) values('쏘나타 2.0 GDI 하이브리드 ',1);
insert into model(model, mkno) values('쏘나타 2.0 하이브리드 ',1);
insert into model(model, mkno) values('쏘나타 2.0 T-GDI ',1);
insert into model(model, mkno) values('싼타페 2.2디젤 4WD(DM) ',1);
insert into model(model, mkno) values('싼타페 2.2디젤 4WD ISG ',1);
insert into model(model, mkno) values('싼타페 2.2디젤 2WD(DM) ',1);
insert into model(model, mkno) values('싼타페 2.2디젤 2WD ISG ',1);
insert into model(model, mkno) values('싼타페 2.0디젤 4WD(DM) ',1);
insert into model(model, mkno) values('싼타페 2.0디젤 4WD ISG ',1);
insert into model(model, mkno) values('싼타페 2.0디젤 2WD(DM) ',1);
insert into model(model, mkno) values('싼타페 2.0디젤 2WD ISG 7인 ',1);
insert into model(model, mkno) values('벨로스터 1.6T-GDI  ',1);
insert into model(model, mkno) values('벨로스터 1.6GDI_6DCT  ',1);
insert into model(model, mkno) values('벨로스터 1.6GDI (2015년형) ',1);
insert into model(model, mkno) values('베라크루즈 3.8 가솔린 4WD ',1);
insert into model(model, mkno) values('베라크루즈 3.0 디젤 4WD ',1);
insert into model(model, mkno) values('베라크루즈 3.0 디젤 2WD ',1);
insert into model(model, mkno) values('맥스크루즈 3.3 GDI 4WD ',1);
insert into model(model, mkno) values('맥스크루즈 3.3 GDI 2WD ',1);
insert into model(model, mkno) values('맥스크루즈 2.2 디젤 4WD ',1);
insert into model(model, mkno) values('맥스크루즈 2.2 디젤 2WD ',1);
insert into model(model, mkno) values('그랜저 3.0 LPI ',1);
insert into model(model, mkno) values('그랜저 3.0 GDI ',1);
insert into model(model, mkno) values('그랜저 2.4 GDI ',1);
insert into model(model, mkno) values('그랜저 2.4 하이브리드 ',1);
insert into model(model, mkno) values('그랜저 2.2 디젤 ',1);
insert into model(model, mkno) values('그랜드 스타렉스 2.5디젤 4WD ',1);
insert into model(model, mkno) values('그랜드 스타렉스 2.5디젤 2WD ',1);
insert into model(model, mkno) values('그랜드 스타렉스 2.5디젤 ',1);
insert into model(model, mkno) values('그랜드 스타렉스 2.4 LPI ',1);

-- 기아
insert into model(model, mkno) values('K9 5.0 GDI', 2);
insert into model(model, mkno) values('K9 3.8 GDI', 2);
insert into model(model, mkno) values('K9 3.3 GDI ', 2);
insert into model(model, mkno) values('K7 3.3 GDI', 2);
insert into model(model, mkno) values('K7 3.0 LPI', 2);
insert into model(model, mkno) values('K7 3.0 GDI', 2);
insert into model(model, mkno) values('K7 2.4 GDI', 2);
insert into model(model, mkno) values('K7 2.4 하이브리드', 2);
insert into model(model, mkno) values('K5(JF) 2.0 TGDI', 2);
insert into model(model, mkno) values('K5(JF) 2.0 LPI 6MT', 2);
insert into model(model, mkno) values('K5(JF) 2.0 LPI 6AT', 2);
insert into model(model, mkno) values('K5(JF) 2.0 가솔린 (18인치)', 2);
insert into model(model, mkno) values('K5(JF) 1.7 디젤 7DCT_ISG ', 2);
insert into model(model, mkno) values('K5(JF) 1.6 T-GDI', 2);
insert into model(model, mkno) values('K5 2.0 T-GDI', 2);
insert into model(model, mkno) values('K5 2.0 LPI', 2);
insert into model(model, mkno) values('K5 2.0 하이브리드', 2);
insert into model(model, mkno) values('K5 2.0 가솔린', 2);
insert into model(model, mkno) values('K3 1.6 T-GDI', 2);
insert into model(model, mkno) values('K3 1.6 GDI ISG', 2);
insert into model(model, mkno) values('K3 1.6 GDI', 2);
insert into model(model, mkno) values('K3 1.6 디젤 ISG', 2);
insert into model(model, mkno) values('프라이드 1.6 GDI ISG', 2);
insert into model(model, mkno) values('프라이드 1.6 GDI', 2);
insert into model(model, mkno) values('프라이드 1.4 디젤', 2);
insert into model(model, mkno) values('프라이드 1.4 가솔린', 2);
insert into model(model, mkno) values('포르테쿠페 2.0', 2);
insert into model(model, mkno) values('포르테쿠페 1.6 GDI', 2);
insert into model(model, mkno) values('포르테 1.6 LPI 하이브리드', 2);
insert into model(model, mkno) values('카렌스 누우 2.0 LPI', 2);
insert into model(model, mkno) values('카렌스 2.0 LPI', 2);
insert into model(model, mkno) values('카렌스 2.0 가솔린', 2);
insert into model(model, mkno) values('카렌스 1.7 디젤 ISG', 2);
insert into model(model, mkno) values('카렌스 1.7 디젤', 2);
insert into model(model, mkno) values('카니발 리무진 2.2 디젤', 2);
insert into model(model, mkno) values('카니발 3.5 가솔린', 2);
insert into model(model, mkno) values('카니발 3.3 GDI', 2);
insert into model(model, mkno) values('카니발 2.2 디젤', 2);
insert into model(model, mkno) values('쏘울 1.6 GDI', 2);
insert into model(model, mkno) values('쏘울 1.6 디젤', 2);
insert into model(model, mkno) values('쏘렌토 2.2 디젤 4WD', 2);
insert into model(model, mkno) values('쏘렌토 2.2 디젤 2WD', 2);
insert into model(model, mkno) values('쏘렌토 2.0 디젤 4WD', 2);
insert into model(model, mkno) values('쏘렌토 2.0 디젤 2WD', 2);
insert into model(model, mkno) values('스포티지 2.0 T-GDI 4WD', 2);
insert into model(model, mkno) values('스포티지 2.0 T-GDI 2WD', 2);
insert into model(model, mkno) values('스포티지 2.0 디젤 4WD', 2);
insert into model(model, mkno) values('스포티지 2.0 디젤 2WD', 2);
insert into model(model, mkno) values('모하비 4.6 가솔린 4WD', 2);
insert into model(model, mkno) values('모하비 3.0 디젤 4WD', 2);
insert into model(model, mkno) values('모하비 3.0 디젤 2WD', 2);
insert into model(model, mkno) values('모닝 1.0 TCI ', 2);
insert into model(model, mkno) values('모닝 1.0 Bi-fuel LPI', 2);
insert into model(model, mkno) values('모닝 1.0 가솔린', 2);
insert into model(model, mkno) values('레이 1.0 TCI', 2);
insert into model(model, mkno) values('레이 1.0 Bi-fuel LPI', 2);
insert into model(model, mkno) values('레이 1.0 가솔린', 2);
insert into model(model, mkno) values('그랜드카니발 2.2 디젤', 2);

-- 르노
insert into model(model, mkno) values('SM7 LPLi', 3);
insert into model(model, mkno) values('SM5 1.5 DIESEL', 3);
insert into model(model, mkno) values('QM5 4WD', 3);
insert into model(model, mkno) values('QM5 2WD', 3);
insert into model(model, mkno) values('QM5 2.0', 3);
insert into model(model, mkno) values('QM3', 3);
insert into model(model, mkno) values('New SM7 3.5', 3);
insert into model(model, mkno) values('New SM7 2.5', 3);
insert into model(model, mkno) values('New SM5 LPLi', 3);
insert into model(model, mkno) values('New SM5 1.6', 3);
insert into model(model, mkno) values('New SM5', 3);
insert into model(model, mkno) values('New SM3 1.6', 3);

-- 쉐보레
insert into model(model, mkno) values('트랙스 1.6 디젤', 4);
insert into model(model, mkno) values('트랙스 1.4', 4);
insert into model(model, mkno) values('크루즈 2.0 디젤', 4);
insert into model(model, mkno) values('크루즈 1.8', 4);
insert into model(model, mkno) values('크루즈 1.4', 4);
insert into model(model, mkno) values('캡티바 2.2 디젤 AWD', 4);
insert into model(model, mkno) values('캡티바 2.0 디젤 FWD', 4);
insert into model(model, mkno) values('올란도 2.0 LPG', 4);
insert into model(model, mkno) values('올란도 2.0 디젤', 4);
insert into model(model, mkno) values('올란도 1.6 디젤', 4);
insert into model(model, mkno) values('알페온 3.0', 4);
insert into model(model, mkno) values('알페온 2.4 하이브리드', 4);
insert into model(model, mkno) values('알페온 2.4', 4);
insert into model(model, mkno) values('아베오 1.4 MT', 4);
insert into model(model, mkno) values('아베오 1.4 AT', 4);
insert into model(model, mkno) values('아베오 1.4', 4);
insert into model(model, mkno) values('스파크밴 1.0 MT', 4);
insert into model(model, mkno) values('스파크밴 1.0 CVT', 4);
insert into model(model, mkno) values('스파크 밴 1.0', 4);
insert into model(model, mkno) values('스파크 1.0 MT', 4);
insert into model(model, mkno) values('스파크 1.0 CVT', 4);
insert into model(model, mkno) values('쉐보레 임팔라 2.5', 4);
insert into model(model, mkno) values('말리부 2.4', 4);
insert into model(model, mkno) values('말리부 2.0 LPG', 4);
insert into model(model, mkno) values('말리부 2.0 디젤', 4);
insert into model(model, mkno) values('말리부 2.0', 4);
insert into model(model, mkno) values('라보롱카고', 4);
insert into model(model, mkno) values('라보5MT', 4);
insert into model(model, mkno) values('다마스밴', 4);
insert into model(model, mkno) values('다마스 5인승', 4);

-- 쌍용
insert into model(model, mkno) values('티볼리 디젤 MT 2WD Short', 5);
insert into model(model, mkno) values('티볼리 디젤 AT 2WD Short', 5);
insert into model(model, mkno) values('티볼리 가솔린 MT 2WD Short', 5);
insert into model(model, mkno) values('티볼리 가솔린 AT 2WD Short', 5);
insert into model(model, mkno) values('코란도C AT AWD', 5);
insert into model(model, mkno) values('코란도C AT 2WD', 5);
insert into model(model, mkno) values('코란도C 2.2 디젤 6MT AWD', 5);
insert into model(model, mkno) values('코란도C 2.2 디젤 6MT 2WD', 5);
insert into model(model, mkno) values('코란도C 2.2 디젤 6AT AWD', 5);
insert into model(model, mkno) values('코란도C 2.2 디젤 6AT 2WD', 5);
insert into model(model, mkno) values('코란도C 2.0DI CDPF AWD', 5);
insert into model(model, mkno) values('코란도C 2.0DI CDPF 4WD 수동 6단 ECO', 5);
insert into model(model, mkno) values('코란도C 2.0DI CDPF 2WD 수동 6단 ECO ', 5);
insert into model(model, mkno) values('코란도스포츠 2.0DI CDPF 4WD 자동6단', 5);
insert into model(model, mkno) values('코란도스포츠 2.0DI CDPF 4WD 수동6단', 5);
insert into model(model, mkno) values('코란도스포츠 2.0DI CDPF 2WD 자동6단', 5);
insert into model(model, mkno) values('코란도스포츠 2.0DI CDPF 2WD 수동6단 ', 5);
insert into model(model, mkno) values('코란도스포츠 2.0 4WD 자동5단', 5);
insert into model(model, mkno) values('코란도스포츠 2.0 2WD 자동5단', 5);
insert into model(model, mkno) values('코란도스포츠 2.0 2WD 수동6단 저공해', 5);
insert into model(model, mkno) values('코란도 투리스모11인승 2.0DI CDPF 4WD 자동5단', 5);
insert into model(model, mkno) values('코란도 투리스모11인승 2.0DI CDPF 2WD 자동5단', 5);
insert into model(model, mkno) values('코란도 투리스모11인승 2.0DI CDPF 2WD 수동6단', 5);
insert into model(model, mkno) values('코란도 투리스모 샤토 9인승 4WD 자동5단', 5);
insert into model(model, mkno) values('코란도 투리스모 샤토 11인승 AT 4WD', 5);
insert into model(model, mkno) values('코란도 투리스모 9인승 AT 4WD', 5);
insert into model(model, mkno) values('코란도 투리스모 9인승 AT 2WD', 5);
insert into model(model, mkno) values('체어맨W 가솔린 5.0 리무진 ', 5);
insert into model(model, mkno) values('체어맨W 가솔린 5.0 2WD ', 5);
insert into model(model, mkno) values('체어맨W 가솔린 3.6 AWD ', 5);
insert into model(model, mkno) values('체어맨W 가솔린 3.6 2WD', 5);
insert into model(model, mkno) values('체어맨W 가솔린 3.2 AWD ', 5);
insert into model(model, mkno) values('체어맨W 가솔린 3.2 2WD ', 5);
insert into model(model, mkno) values('체어맨H 가솔린 3.2', 5);
insert into model(model, mkno) values('체어맨H 가솔린 2.8', 5);
insert into model(model, mkno) values('로디우스11인승 2.0DI CDPF 4WD 자동 5단', 5);
insert into model(model, mkno) values('로디우스 11인승 2.0DI CDPF 2WD 자동 5단', 5);
insert into model(model, mkno) values('로디우스 11인승 2.0DI CDPF 2WD 수동6단', 5);
insert into model(model, mkno) values('렉스턴 2.0DI CDPF 4WD 자동5단', 5);
insert into model(model, mkno) values('렉스턴 2.0DI CDPF 4WD 수동6단 ', 5);
insert into model(model, mkno) values('렉스턴 2.0DI CDPF 2WD 자동5단', 5);
insert into model(model, mkno) values('렉스턴 2.0DI CDPF 2WD 수동6단 ', 5);

-- 차종별 공인 연비 테이블
insert into official(mdno, fuel, effi) values(1, '휘발유', 11.9);
insert into official(mdno, fuel, effi) values(2, '경유', 16.2);
insert into official(mdno, fuel, effi) values(3, '휘발유', 11.4);
insert into official(mdno, fuel, effi) values(4, '경유', 15.5);
insert into official(mdno, fuel, effi) values(5, '휘발유', 11.8);
insert into official(mdno, fuel, effi) values(6, '경유', 17.3);
insert into official(mdno, fuel, effi) values(7, '경유', 9.2);
insert into official(mdno, fuel, effi) values(8, '휘발유', 10.3);
insert into official(mdno, fuel, effi) values(9, '경유', 13.8);
insert into official(mdno, fuel, effi) values(10, '경유', 14.1);
insert into official(mdno, fuel, effi) values(11, '경유', 14.4);
insert into official(mdno, fuel, effi) values(12, '경유', 13.8);
insert into official(mdno, fuel, effi) values(13, '경유', 15.6);
insert into official(mdno, fuel, effi) values(14, '휘발유', 8.7);
insert into official(mdno, fuel, effi) values(15, '휘발유', 9.9);
insert into official(mdno, fuel, effi) values(16, '휘발유', 8.5);
insert into official(mdno, fuel, effi) values(17, '휘발유', 9);
insert into official(mdno, fuel, effi) values(18, '휘발유', 8.8);
insert into official(mdno, fuel, effi) values(19, '휘발유', 9.2);
insert into official(mdno, fuel, effi) values(20, '휘발유', 14.1);
insert into official(mdno, fuel, effi) values(21, '휘발유', 14);
insert into official(mdno, fuel, effi) values(22, '경유', 19);
insert into official(mdno, fuel, effi) values(23, '경유', 18);
insert into official(mdno, fuel, effi) values(24, '휘발유', 7.4);
insert into official(mdno, fuel, effi) values(25, '휘발유', 8.4);
insert into official(mdno, fuel, effi) values(26, '휘발유', 8.1);
insert into official(mdno, fuel, effi) values(27, '휘발유', 8.9);
insert into official(mdno, fuel, effi) values(28, '휘발유', 9.5);
insert into official(mdno, fuel, effi) values(29, '휘발유', 9.5);
insert into official(mdno, fuel, effi) values(30, '휘발유', 12.4);
insert into official(mdno, fuel, effi) values(31, 'LPG', 11.7);
insert into official(mdno, fuel, effi) values(32, '휘발유', 14.1);
insert into official(mdno, fuel, effi) values(33, '경유', 16.2);
insert into official(mdno, fuel, effi) values(34, '경유', 18.5);
insert into official(mdno, fuel, effi) values(35, '휘발유', 11.5);
insert into official(mdno, fuel, effi) values(36, 'LPG', 10.1);
insert into official(mdno, fuel, effi) values(37, '휘발유', 11.6);
insert into official(mdno, fuel, effi) values(38, '경유', 16.5);
insert into official(mdno, fuel, effi) values(39, '휘발유', 13.1);
insert into official(mdno, fuel, effi) values(40, 'LPG', 9.3);
insert into official(mdno, fuel, effi) values(41, '휘발유', 17.7);
insert into official(mdno, fuel, effi) values(42, '휘발유', 16.8);
insert into official(mdno, fuel, effi) values(43, '휘발유', 10.8);
insert into official(mdno, fuel, effi) values(44, '경유', 12.4);
insert into official(mdno, fuel, effi) values(45, '경유', 11.6);
insert into official(mdno, fuel, effi) values(46, '경유', 13.8);
insert into official(mdno, fuel, effi) values(47, '경유', 12.8);
insert into official(mdno, fuel, effi) values(48, '경유', 13);
insert into official(mdno, fuel, effi) values(49, '경유', 11.7);
insert into official(mdno, fuel, effi) values(50, '경유', 14.4);
insert into official(mdno, fuel, effi) values(51, '경유', 13.8);
insert into official(mdno, fuel, effi) values(52, '휘발유', 12.3);
insert into official(mdno, fuel, effi) values(53, '휘발유', 13.3);
insert into official(mdno, fuel, effi) values(54, '휘발유', 12.4);
insert into official(mdno, fuel, effi) values(55, '휘발유', 7.3);
insert into official(mdno, fuel, effi) values(56, '경유', 10.7);
insert into official(mdno, fuel, effi) values(57, '경유', 11.2);
insert into official(mdno, fuel, effi) values(58, '휘발유', 8.5);
insert into official(mdno, fuel, effi) values(59, '휘발유', 8.9);
insert into official(mdno, fuel, effi) values(60, '경유', 11.3);
insert into official(mdno, fuel, effi) values(61, '경유', 11.9);
insert into official(mdno, fuel, effi) values(62, 'LPG', 8.2);
insert into official(mdno, fuel, effi) values(63, '휘발유', 10.4);
insert into official(mdno, fuel, effi) values(64, '휘발유', 11.1);
insert into official(mdno, fuel, effi) values(65, '휘발유', 16);
insert into official(mdno, fuel, effi) values(66, '경유', 13.8);
insert into official(mdno, fuel, effi) values(67, '경유', 8.7);
insert into official(mdno, fuel, effi) values(68, '경유', 11.3);
insert into official(mdno, fuel, effi) values(69, '경유', 9.5);
insert into official(mdno, fuel, effi) values(70, 'LPG', 6.3);
insert into official(mdno, fuel, effi) values(71, '휘발유', 7.6);
insert into official(mdno, fuel, effi) values(72, '휘발유', 9.3);
insert into official(mdno, fuel, effi) values(73, '휘발유', 9.4);
insert into official(mdno, fuel, effi) values(74, '휘발유', 10);
insert into official(mdno, fuel, effi) values(75, 'LPG', 8.2);
insert into official(mdno, fuel, effi) values(76, '휘발유', 10.4);
insert into official(mdno, fuel, effi) values(77, '휘발유', 11.3);
insert into official(mdno, fuel, effi) values(78, '휘발유', 16);
insert into official(mdno, fuel, effi) values(79, '휘발유', 10.8);
insert into official(mdno, fuel, effi) values(80, 'LPG', 10);
insert into official(mdno, fuel, effi) values(81, 'LPG', 9.6);
insert into official(mdno, fuel, effi) values(82, '휘발유', 12);
insert into official(mdno, fuel, effi) values(83, '경유', 16);
insert into official(mdno, fuel, effi) values(84, '휘발유', 13.1);
insert into official(mdno, fuel, effi) values(85, '휘발유', 10.3);
insert into official(mdno, fuel, effi) values(86, 'LPG', 9.3);
insert into official(mdno, fuel, effi) values(87, '휘발유', 16.8);
insert into official(mdno, fuel, effi) values(88, '휘발유', 11.9);
insert into official(mdno, fuel, effi) values(89, '휘발유', 11.5);
insert into official(mdno, fuel, effi) values(90, '휘발유', 14.5);
insert into official(mdno, fuel, effi) values(91, '휘발유', 14);
insert into official(mdno, fuel, effi) values(92, '경유', 16.2);
insert into official(mdno, fuel, effi) values(93, '휘발유', 14.3);
insert into official(mdno, fuel, effi) values(94, '휘발유', 14.7);
insert into official(mdno, fuel, effi) values(95, '경유', 19);
insert into official(mdno, fuel, effi) values(96, '휘발유', 14.5);
insert into official(mdno, fuel, effi) values(97, '휘발유', 10.9);
insert into official(mdno, fuel, effi) values(98, '휘발유', 13);
insert into official(mdno, fuel, effi) values(99, 'LPG', 14);
insert into official(mdno, fuel, effi) values(100, 'LPG', 9.5);
insert into official(mdno, fuel, effi) values(101, 'LPG', 7.7);
insert into official(mdno, fuel, effi) values(102, '휘발유', 9.5);
insert into official(mdno, fuel, effi) values(103, '경유', 15.7);
insert into official(mdno, fuel, effi) values(104, '경유', 13.2);
insert into official(mdno, fuel, effi) values(105, '경유', 11.3);
insert into official(mdno, fuel, effi) values(106, '휘발유', 8.2);
insert into official(mdno, fuel, effi) values(107, '휘발유', 8);
insert into official(mdno, fuel, effi) values(108, '경유', 10.3);
insert into official(mdno, fuel, effi) values(109, '휘발유', 12.3);
insert into official(mdno, fuel, effi) values(110, '경유', 14.1);
insert into official(mdno, fuel, effi) values(111, '경유', 12);
insert into official(mdno, fuel, effi) values(112, '경유', 12.8);
insert into official(mdno, fuel, effi) values(113, '경유', 12.3);
insert into official(mdno, fuel, effi) values(114, '경유', 14.4);
insert into official(mdno, fuel, effi) values(115, '휘발유', 9.2);
insert into official(mdno, fuel, effi) values(116, '휘발유', 9.7);
insert into official(mdno, fuel, effi) values(117, '경유', 12.4);
insert into official(mdno, fuel, effi) values(118, '경유', 13.8);
insert into official(mdno, fuel, effi) values(119, '휘발유', 7);
insert into official(mdno, fuel, effi) values(120, '경유', 10.3);
insert into official(mdno, fuel, effi) values(121, '경유', 10.7);
insert into official(mdno, fuel, effi) values(122, '휘발유', 14);
insert into official(mdno, fuel, effi) values(123, 'LPG', 13.2);
insert into official(mdno, fuel, effi) values(124, '휘발유', 15.2);
insert into official(mdno, fuel, effi) values(125, '휘발유', 13.2);
insert into official(mdno, fuel, effi) values(126, 'LPG', 10.8);
insert into official(mdno, fuel, effi) values(127, '휘발유', 13.5);
insert into official(mdno, fuel, effi) values(128, '경유', 10.9);
insert into official(mdno, fuel, effi) values(129, 'LPG', 8.6);
insert into official(mdno, fuel, effi) values(130, '경유', 16.5);
insert into official(mdno, fuel, effi) values(131, '경유', 12.8);
insert into official(mdno, fuel, effi) values(132, '경유', 13.2);
insert into official(mdno, fuel, effi) values(133, '휘발유', 10.6);
insert into official(mdno, fuel, effi) values(134, '경유', 18.5);
insert into official(mdno, fuel, effi) values(135, '휘발유', 9.4);
insert into official(mdno, fuel, effi) values(136, '휘발유', 10.2);
insert into official(mdno, fuel, effi) values(137, 'LPG', 9.6);
insert into official(mdno, fuel, effi) values(138, '휘발유', 13);
insert into official(mdno, fuel, effi) values(139, '휘발유', 12.6);
insert into official(mdno, fuel, effi) values(140, '휘발유', 15);
insert into official(mdno, fuel, effi) values(141, '경유', 14.7);
insert into official(mdno, fuel, effi) values(142, '휘발유', 12.2);
insert into official(mdno, fuel, effi) values(143, '경유', 13.1);
insert into official(mdno, fuel, effi) values(144, '휘발유', 11.3);
insert into official(mdno, fuel, effi) values(145, '휘발유', 12.6);
insert into official(mdno, fuel, effi) values(146, '경유', 9.8);
insert into official(mdno, fuel, effi) values(147, '경유', 10.8);
insert into official(mdno, fuel, effi) values(148, 'LPG', 8);
insert into official(mdno, fuel, effi) values(149, '경유', 12);
insert into official(mdno, fuel, effi) values(150, '경유', 13.5);
insert into official(mdno, fuel, effi) values(151, '휘발유', 9.3);
insert into official(mdno, fuel, effi) values(152, '휘발유', 12.1);
insert into official(mdno, fuel, effi) values(153, '휘발유', 10.8);
insert into official(mdno, fuel, effi) values(154, '휘발유', 14.9);
insert into official(mdno, fuel, effi) values(155, '휘발유', 13.1);
insert into official(mdno, fuel, effi) values(156, '휘발유', 12.6);
insert into official(mdno, fuel, effi) values(157, '휘발유', 16.8);
insert into official(mdno, fuel, effi) values(158, '휘발유', 15.3);
insert into official(mdno, fuel, effi) values(159, '휘발유', 15.4);
insert into official(mdno, fuel, effi) values(160, '휘발유', 16.8);
insert into official(mdno, fuel, effi) values(161, '휘발유', 15.3);
insert into official(mdno, fuel, effi) values(162, '휘발유', 10.5);
insert into official(mdno, fuel, effi) values(163, '휘발유', 10.8);
insert into official(mdno, fuel, effi) values(164, 'LPG', 8.3);
insert into official(mdno, fuel, effi) values(165, '경유', 13.3);
insert into official(mdno, fuel, effi) values(166, '휘발유', 11.6);
insert into official(mdno, fuel, effi) values(167, 'LPG', 8.9);
insert into official(mdno, fuel, effi) values(168, 'LPG', 8.9);
insert into official(mdno, fuel, effi) values(169, 'LPG', 9.2);
insert into official(mdno, fuel, effi) values(170, 'LPG', 9);
insert into official(mdno, fuel, effi) values(171, '경유', 17.3);
insert into official(mdno, fuel, effi) values(172, '경유', 15.3);
insert into official(mdno, fuel, effi) values(173, '휘발유', 12.3);
insert into official(mdno, fuel, effi) values(174, '휘발유', 12);
insert into official(mdno, fuel, effi) values(175, '경유', 11.6);
insert into official(mdno, fuel, effi) values(176, '경유', 12.8);
insert into official(mdno, fuel, effi) values(177, '경유', 14.4);
insert into official(mdno, fuel, effi) values(178, '경유', 15.2);
insert into official(mdno, fuel, effi) values(179, '경유', 12.5);
insert into official(mdno, fuel, effi) values(180, '경유', 13.3);
insert into official(mdno, fuel, effi) values(181, '경유', 14.1);
insert into official(mdno, fuel, effi) values(182, '경유', 16.1);
insert into official(mdno, fuel, effi) values(183, '경유', 17.2);
insert into official(mdno, fuel, effi) values(184, '경유', 11.2);
insert into official(mdno, fuel, effi) values(185, '경유', 12.8);
insert into official(mdno, fuel, effi) values(186, '경유', 11.6);
insert into official(mdno, fuel, effi) values(187, '경유', 13.3);
insert into official(mdno, fuel, effi) values(188, '경유', 11.4);
insert into official(mdno, fuel, effi) values(189, '경유', 11.8);
insert into official(mdno, fuel, effi) values(190, '경유', 12.5);
insert into official(mdno, fuel, effi) values(191, '경유', 11.3);
insert into official(mdno, fuel, effi) values(192, '경유', 12);
insert into official(mdno, fuel, effi) values(193, '경유', 13.2);
insert into official(mdno, fuel, effi) values(194, '경유', 10.5);
insert into official(mdno, fuel, effi) values(195, '경유', 10.5);
insert into official(mdno, fuel, effi) values(196, '경유', 11.3);
insert into official(mdno, fuel, effi) values(197, '경유', 12);
insert into official(mdno, fuel, effi) values(198, '휘발유', 7.5);
insert into official(mdno, fuel, effi) values(199, '휘발유', 7.6);
insert into official(mdno, fuel, effi) values(200, '휘발유', 7.5);
insert into official(mdno, fuel, effi) values(201, '휘발유', 8);
insert into official(mdno, fuel, effi) values(202, '휘발유', 7.6);
insert into official(mdno, fuel, effi) values(203, '휘발유', 8.1);
insert into official(mdno, fuel, effi) values(204, '휘발유', 8.5);
insert into official(mdno, fuel, effi) values(205, '휘발유', 8.4);
insert into official(mdno, fuel, effi) values(206, '경유', 11.3);
insert into official(mdno, fuel, effi) values(207, '경유', 12);
insert into official(mdno, fuel, effi) values(208, '경유', 13.2);
insert into official(mdno, fuel, effi) values(209, '경유', 11.7);
insert into official(mdno, fuel, effi) values(210, '경유', 12.9);
insert into official(mdno, fuel, effi) values(211, '경유', 12.2);
insert into official(mdno, fuel, effi) values(212, '경유', 13.3);

